version: 2.1

jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk11:jdk-11.0.11_9-centos-slim
        auth:
          username: peregin
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/project

    environment:
      JVM_OPTS: -Xmx3072m
      SBT_VERSION: 1.5.2

    steps:
      - run:
          name: get sbt binary
          command: |
            export SBT_OPTS="-Dfile.encoding=UTF-8"
            curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" > $HOME/sbt.tgz
            tar zxf $HOME/sbt.tgz -C $HOME
            rm /usr/local/bin/sbt || true
            ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt

      - checkout

      - restore_cache:
          keys: v1-dependencies-{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          key: v1-dependencies--{{ checksum "build.sbt" }}
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm

      - run: cat /dev/null | sbt test:test
