version: 2.1

jobs:
  build:
    docker:
      - image: peregin/circleci:latest
        auth:
          username: peregin
          password: $DOCKERHUB_PASSWORD
        user: circleci

    working_directory: ~/project

    environment:
      JVM_OPTS: -Xmx3072m
      SBT_VERSION: 1.5.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          key: v1-{{ checksum "build.sbt" }}
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm

      - run: cat /dev/null | sbt test:test

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /circleci-.*/