version: 2.1

defaults:
  working_directory: ~/project
  cache_key: &cache_key 'v1-{{ checksum "checksums.txt" }}'

executors:
  ci-executor:
    docker:
      - image: peregin/circleci:latest
        user: circleci
      - image: postgres:16
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: postgres
    environment:
      JVM_OPTS: -Xmx3072m
  ci-deploy-executor:
    docker:
      - image: peregin/circleci:latest
        user: circleci
    environment:
      JVM_OPTS: -Xmx3072m
  ci-min:
    docker:
      - image: cimg/base:2024.11

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: .circleci/cachekey.sh checksums.txt
      - restore_cache:
          key: *cache_key
      - run: sbt Compile/compile
      - run: sbt Test/test
      - save_cache:
          key: *cache_key
          paths:
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_web-backend:
    executor: ci-deploy-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: build fat jar
          command: sbt "service/assembly"
      - run:
          name: deploy backend
          command: ./deploy.sh

  deploy_crawler-backend:
    executor: ci-deploy-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy crawler-backend
          command: sbt "crawler-service/docker:publish"

  deploy_web-frontend:
    executor: ci-deploy-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy web-frontend
          command: cd web-front && ./deploy.sh

  restart_stack:
    docker:
      - image: cimg/base:2024.11
    resource_class: small
    steps:
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOYER_USER"@velocorner.com '/opt/velocorner/deploy.sh'

workflows:
  ci_cd:
    jobs:
      - build
      - deploy_web-backend:
          context: peregin
          requires:
            - build
          filters:
            branches:
              only: /^master.*/
#      - deploy_crawler-backend:
#          requires:
#            - build
#          filters:
#            branches:
#              only: /^master.*/
#      - deploy_web-frontend:
#          requires:
#            - build
#          filters:
#            branches:
#              only: /^master.*/
      - restart_stack:
          context: peregin
          requires:
            - deploy_web-backend
#            - deploy_crawler-backend
#            - deploy_web-frontend
