version: 2.1

defaults:
  working_directory: ~/project
  cache_key: &cache_key 'v1-{{ checksum "checksums.txt" }}'

executors:
  ci-executor:
    docker:
      - image: peregin/circleci:latest
        auth:
          username: peregin
          password: $DOCKERHUB_PASSWORD
        user: circleci
    environment:
      JVM_OPTS: -Xmx3072m

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: .circleci/cachekey.sh checksums.txt
      - restore_cache:
          key: *cache_key
      - run: sbt Compile/compile Test/compile
      - save_cache:
          key: *cache_key
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: sbt test:test

  deploy_web-backend:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: setup git identity
          command: |
            git config --global user.name "Deploy CI"
            git config --global user.email "velocorner.com@gmail.com"
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy web-backend
          command: sbt "release skip-tests with-defaults" && git push --tags

  deploy_web-frontend:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: setup git identity
          command: |
            git config --global user.name "Deploy CI"
            git config --global user.email "velocorner.com@gmail.com"
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy web-frontend
          command: cd web-front && ./deploy.sh && git push --tags

  restart_stack:
    executor: ci-executor
    steps:
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOYER_USER"@velocorner.com '/opt/velocorner/deploy.sh'

workflows:
  ci_cd:
    jobs:
      - build
      - deploy_web-backend:
          requires:
            - build
          filters:
            branches:
              only: /master.*/
      - deploy_web-frontend:
          requires:
            - build
          filters:
            branches:
              only: /master.*/
      - restart_stack:
          requires:
            - deploy_web-backend
            - deploy_web-frontend