version: 2.1

defaults:
  working_directory: ~/project
  cache_key: &cache_key 'v1-{{ checksum "checksums.txt" }}'

executors:
  ci-executor:
    docker:
      - image: peregin/circleci:latest
        auth:
          username: peregin
          password: $DOCKERHUB_PASSWORD
        user: circleci
    environment:
      JVM_OPTS: -Xmx3072m

jobs:

  build:
    executor: ci-executor
    steps:
      - checkout
      - run: .circleci/cachekey.sh checksums.txt
      - restore_cache:
          key: *cache_key
      - run: sbt test:compile
      - save_cache:
          key: *cache_key
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: sbt test:test

  deploy_web-app:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: deploy web-app
          command: sbt web-app/docker:publish


  build1:
    executor: ci-executor
    steps:
      - run: echo "build1"

  build2:
    executor: ci-executor
    steps:
      - run: echo "build2"

  deploy1:
    executor: ci-executor
    steps:
      - run: echo "deploy1"

parameters:
  service1-changed:
    type: boolean
    default: false
  service2-changed:
    type: boolean
    default: false

workflows:
  version: 2
  service1:
    when: << service1-changed >>
    jobs:
      - build1
  service2:
    when: << service2-changed >>
    jobs:
      - build2
  ci_cd:
    jobs:
      - build1:
          filters:
            branches:
              only: /circleci-.*/
      - deploy1:
          requires:
            - build1
            - build2