version: 2.1

jobs:
  build:
    docker:
      - image: moia/scala-on-circleci:java11-2.13.1-1.3.8

    working_directory: ~/project

    environment:
      JVM_OPTS: -Xmx3072m
      SBT_VERSION: 1.5.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:test
