version: 2.1

orbs:
  path-filtering: circleci/path-filtering@1.0.0

parameters:
  run-build:
    type: boolean
    default: false

defaults:
  working_directory: ~/project
  cache_key: &cache_key 'v1-{{ checksum "checksums.txt" }}'

executors:
  ci-executor:
    docker:
      - image: peregin/circleci:latest
        user: circleci
      - image: postgres:16
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: postgres
    environment:
      JVM_OPTS: -Xmx3072m
  ci-deploy-executor:
    docker:
      - image: peregin/circleci:latest
        user: circleci
    environment:
      JVM_OPTS: -Xmx3072m
  ci-min:
    docker:
      - image: cimg/base:2024.11

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: .circleci/cachekey.sh checksums.txt
      - restore_cache:
          key: *cache_key
      - run: sbt Compile/compile
      - run: sbt Test/test
      - save_cache:
          key: *cache_key
          paths:
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_web-backend:
    executor: ci-deploy-executor
    environment:
      BUILDX_VERSION: 0.17.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: setup git identity
          command: |
            git config --global user.name "Deploy CI"
            git config --global user.email "velocorner.com@gmail.com"
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy web-backend
          command: |
            sbt "release skip-tests with-defaults"
      - run:
          name: upload version tags
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts && git push --tags --quiet https://peregin:${GH_TOKEN}@github.com/peregin/velocorner.com.git "$CIRCLE_BRANCH"

  deploy_crawler-backend:
    executor: ci-deploy-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy crawler-backend
          command: sbt "crawler-service/docker:publish"

  deploy_web-frontend:
    executor: ci-deploy-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: setup git identity
          command: |
            git config --global user.name "Deploy CI"
            git config --global user.email "velocorner.com@gmail.com"
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy web-frontend
          command: |
            docker buildx inspect multi-arch-builder
            cd web-front && ./deploy.sh

  restart_stack:
    docker:
      - image: cimg/base:2024.11
    resource_class: small
    steps:
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOYER_USER"@velocorner.com '/opt/velocorner/deploy.sh'

workflows:
  setup:
    unless: << pipeline.parameters.run-build >>
    jobs:
      - path-filtering/filter:
          mapping: |
            data-provider/.* run-build true
            web-app/.* run-build true
            build.sbt run-build true
            project/.* run-build true

  ci_cd:
    when: << pipeline.parameters.run-build >>
    jobs:
      - build
      - deploy_web-backend:
          context: peregin
          requires:
            - build
          filters:
            branches:
              only: /^master.*/
#      - deploy_crawler-backend:
#          requires:
#            - build
#          filters:
#            branches:
#              only: /^master.*/
#      - deploy_web-frontend:
#          requires:
#            - build
#          filters:
#            branches:
#              only: /^master.*/
      - restart_stack:
          context: peregin
          requires:
            - deploy_web-backend
#            - deploy_crawler-backend
#            - deploy_web-frontend
