version: 2.1

jobs:
  build:
    docker:
      - image: moia/scala-on-circleci:java11-2.13.1-1.3.8
      # - image: circleci/postgres:9.4

    working_directory: ~/project

    environment:
      JVM_OPTS: -Xmx3072m
      SBT_VERSION: 1.4.7

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # run tests!
      - run: cat /dev/null | sbt test:test
