version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
#setup: true

# the continuation orb is required in order to use dynamic configuration
#orbs:
#  continuation: circleci/continuation@0.1.2

defaults:
  working_directory: ~/project
  cache_key: &cache_key 'v1-{{ checksum "checksums.txt" }}'

executors:
  ci-executor:
    docker:
      - image: peregin/circleci:latest
        auth:
          username: peregin
          password: $DOCKERHUB_PASSWORD
        user: circleci
    environment:
      JVM_OPTS: -Xmx3072m

jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      - run: .circleci/cachekey.sh checksums.txt
      - restore_cache:
          key: *cache_key
      - run: sbt test:compile
      - save_cache:
          key: *cache_key
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.sbt/launchers
            - ~/.cache/coursier
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: sbt test:test

  deploy_web-app:
    executor: ci-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: deploy web-app
          command: sbt web-app/docker:publish


  build1:
    executor: ci-executor
    steps:
      - run: echo "build1"

  build2:
    executor: ci-executor
    steps:
      - run: echo "build2"

  deploy1:
    executor: ci-executor
    steps:
      - run: echo "deploy1"

parameters:
  service1-changed:
    type: boolean
    default: false
  service2-changed:
    type: boolean
    default: true

workflows:
  service1:
    when: << pipeline.parameters.service1-changed >>
    jobs:
      - build1
          requires:
            - deploy_prod_request
  service2:
    when: << pipeline.parameters.service2-changed >>
    jobs:
      - build2
  ci_cd:
    jobs:
      - deploy_prod_request:
          type: approval
      - deploy_prod:
          filters:
            branches:
              only: /circleci-.*/
          #requires:
           # - build1
           # - build2