/*
 * This source file was generated by the Gradle 'init' task
 */
package velocorner.backend

import org.junit.jupiter.api.Test
import kotlin.test.assertNotNull

class ServiceAppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = ServiceApp()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
